name: deploy-main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npm run generate

      - name: Build TypeScript
        run: npm run build

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "$EC2_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          cat >>~/.ssh/config <<END
          Host NerdHack
            HostName $EC2_HOST
            User $EC2_USER
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          END
        env:
          EC2_USER: ubuntu
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

      - name: Sync files with EC2
        run: |
          ssh NerdHack 'mkdir -p /opt/app'
          rsync -avz --delete \
            --exclude=node_modules \
            --exclude=.git \
            --exclude=*.log \
            ./ NerdHack:/opt/app/

      - name: Install dependencies on EC2
        run: |
          ssh NerdHack 'cd /opt/app && npm ci --omit=dev'

      - name: Setup systemd service (first-time only)
        run: |
          ssh NerdHack 'if [ ! -f /etc/systemd/system/app.service ]; then
            echo "[Unit]
            Description=Nerdy Hack team3
            After=network.target

            [Service]
            User=ubuntu
            ExecStart=/usr/bin/npm run start --prefix /opt/app/
            Restart=always

            [Install]
            WantedBy=multi-user.target" | sudo tee /etc/systemd/system/app.service
            sudo systemctl daemon-reload
            sudo systemctl enable app
          fi'

      - name: Restart systemd service
        run: ssh NerdHack 'sudo systemctl restart app'
